version: '3'
services:
  vote-app:
    image: yakhub4881/voting
    container_name: vote-app
    ports:
      - 5000:80
  
  result-app:
    image: yakhub4881/result
    container_name: result-app
    ports:
      - 5001:80

  worker-app:
    image: yakhub4881/worker
    container_name: wroker-app
  
  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres:9.4
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres