apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-app
  template:
    metadata:
      name: redis-app
    spec:
      containers:
      - image: redis
        name: redis-container
        ports:
          - containerPort: 6379

---
apiVersion: v1 
kind: Service 
metadata:
  name: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-app