apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app
  template:
    metadata:
      name: result-app
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: result-container
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31000
  selector:
    name: result-app