apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        app: result-app
    spec:
      containers:
      - image: yakhub4881/result
        name: result-container
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: result-app