apiVersion: apps/v1
kind: Deployment
metadata:
    name: vote-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: vote-app
  template:
    metadata:
        name: vote-app
    spec:
      containers:
      - image: kodekloud/examplevotingapp_vote
        name: vote-container
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    name: vote-app
  