apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        app: worker-app
    spec:
      containers:
        - image: kodekloud/examplevotingapp_worker
          name: worker-container